import {Simulation,ModuleSimulation,stations,organizations} from './simulation.js';
import {FactoryScene} from './scene.js';
async function startApp(){
const $=id=>document.getElementById(id);let sim=new Simulation();const entities=[...organizations,...stations];let factory=null;let selected='discovery';
const time=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function selectStation(id){const s=entities.find(s=>s.id===id);if(!s)return;selected=id;factory?.select(id);$('stationPicker').value=id;$('stationNumber').textContent=s.kind==='organization'?'EMPRESA':`${String(stations.indexOf(s)+1).padStart(2,'0')} / ${String(stations.length).padStart(2,'0')}`;$('stationTitle').textContent=s.name;$('stationRole').textContent=s.role;
 $('stationContent').innerHTML=`<p class="description">${esc(s.description)}</p>${s.parent?`<div class="organization-context"><span>Empresa</span><strong>${esc(organizations.find(o=>o.id===s.parent).name)}</strong></div>`:s.children?`<div class="organization-context"><span>Área integrante</span><strong>${esc(stations.find(a=>a.id===s.children[0]).name)}</strong></div>`:''}<div class="info-block"><h3>Pessoas e agentes</h3><div class="people">${s.people.map((p,i)=>`<div class="person-row"><span class="avatar">${String(i+1).padStart(2,'0')}</span><span>${esc(p)}</span></div>`).join('')}</div></div><div class="info-block"><h3>Capacidades e conexões</h3><div class="tags">${s.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div><div class="info-block"><h3>Artefatos e evidências</h3><div class="file-list">${s.files.map(f=>`<code>${esc(f)}</code>`).join('')}</div></div>${s.concept?'<div class="concept">VISÃO CONCEITUAL · Esta estação ilustra a arquitetura proposta. Não representa uma integração ativa.</div>':''}`;
}
function updateUI(){const p=sim.phase;const module=sim.key==='module';const current=module?sim.selectedEpisode:null;
 $('flowPanel').classList.toggle('module-mode',module);$('flowScope').textContent=module?'MÓDULO EM DESENVOLVIMENTO':'EPISÓDIO DE DESENVOLVIMENTO';$('eventScope').textContent=module?'EVENTOS DO MÓDULO':'EVENTOS DO EPISÓDIO';
 $('moduleSummary').hidden=!module;$('episodeContext').hidden=!module;$('dependencyNote').hidden=!current?.blocked;
 if(module){const feature=sim.scenario.features.find(f=>f.id===current.feature);$('episodeContext').textContent=`${feature.id} · ${feature.name} → ${current.id} · ${current.name}`;$('dependencyNote').textContent=`Bloqueado: aguarda entrega de ${sim.missing(current).join(', ')}.`;
 $('moduleSummary').innerHTML=`<div class="module-totals"><span>4 funcionalidades</span><span>6 episódios</span><span id="activeEpisodes">${sim.activeWork.length} em andamento</span><span>${sim.episodes.filter(e=>e.blocked).length} bloqueados</span><span>${sim.episodes.filter(e=>e.waiting).length} gates pendentes</span><strong>${sim.validatedFeatures}/4 funcionalidades validadas</strong></div><p>Recorte ilustrativo de um módulo em andamento · planos anteriores já simulados. Selecione um card para acompanhar o episódio e aprovar seus gates.</p>`;}
 $('kanbanNote').textContent=module?'Cada episódio avança por suas próprias evidências. Dependências aguardam entrega; gates pendentes afetam apenas o respectivo card.':'O estado acompanha eventos do trabalho. Não depende de mover cartões manualmente.';$('episodeTitle').textContent=`${module?sim.scenario.id:sim.episodeId} · ${sim.scenario.name}`;$('phaseTitle').textContent=p.title;$('phaseDescription').textContent=p.description;$('phaseKind').textContent=p.kind;$('artifactActive').textContent=p.artifact;$('phaseCount').textContent=`${String(sim.index+1).padStart(2,'0')} / ${sim.phaseCount}`;$('evidenceHint').textContent=p.event;$('approval').hidden=!sim.waiting;$('approvalText').textContent=p.gate||'';$('runningTag').textContent=!sim.running?'Simulação pausada':module?(sim.completed?'Módulo validado':`${sim.activeWork.length} episódios em andamento`):sim.waiting?'Aguardando decisão':'Em funcionamento';
 const cols=['Pronto','Em execução','Verificação','Entrega','Resultado'];
 const focused=document.activeElement?.dataset.episode;
 $('kanban').innerHTML=cols.map((name,i)=>{const cards=module?sim.episodes.filter(e=>e.phases[e.index].column===i):[];
 return `<div class="kanban-col"><h3>${name}<span>${module?cards.length:i===p.column?1:0}</span></h3>${module?cards.map(e=>{
 const ep=e.phases[e.index],f=sim.scenario.features.find(f=>f.id===e.feature);const state=e.done?'Validado':e.blocked?`Aguarda ${sim.missing(e).join(', ')}`:e.waiting?'Gate humano pendente':'Em andamento';
 return `<button type="button" class="kanban-card module-card ${e.id===sim.episodeId?'selected':''}" data-episode="${e.id}" aria-pressed="${e.id===sim.episodeId}"><span class="card-feature">${esc(f.id)} · ${esc(f.name)}</span><strong>${e.id}</strong><span class="card-name">${esc(e.name)}</span><small>${esc(ep.title)}</small><span class="card-state ${e.blocked||e.waiting?'pending':''}">${esc(state)}</span><span class="card-progress"><i data-progress="${e.id}" style="width:${Math.min(100,e.phaseTime/ep.duration*100)}%"></i></span></button>`;
 }).join(''):i===p.column?`<div class="kanban-card"><strong>${sim.episodeId}</strong><br>${esc(sim.scenario.name)}<small>${sim.waiting?'Gate humano pendente':'Estado inferido · '+p.skill}</small></div>`:''}${!module&&i===4?'<div class="kanban-card ambient">Portal v2.8.4<br>Operação contínua</div>':''}</div>`;}).join('');
 if(focused)$('kanban').querySelector(`[data-episode="${focused}"]`)?.focus({preventScroll:true});
 $('metrics').innerHTML=(module?[
 ['Versão em produção',sim.version,`${sim.deployments}/6 entregas incrementais simuladas`],
 ['Custo de IA no módulo',`US$ ${sim.cost.toFixed(2).replace('.',',')}`,`${Math.round(sim.tokens/1000)} mil tokens fictícios · desde o recorte inicial`],
 ['Funcionalidades validadas',`${sim.validatedFeatures}/4`,'Cada funcionalidade reúne um ou mais episódios'],
 ['Trabalho em paralelo',`${sim.activeWork.length}/6`,'Episódios em andamento · aguardas não interrompem os demais']
 ]:[['Versão em produção',sim.version,`${sim.deployments} ${sim.deployments===1?'liberação':'liberações'} simulada${sim.deployments===1?'':'s'} · operação contínua`],['Custo de IA no fluxo',`US$ ${sim.cost.toFixed(2).replace('.',',')}`,`${Math.round(sim.tokens/1000)} mil tokens fictícios · sem avaliação individual`],[sim.scenario.metric,sim.completed?sim.scenario.result:sim.scenario.baseline,sim.completed?sim.scenario.explanation:'Referência inicial fictícia · hipótese em validação'],['Retrabalho observado',String(sim.rework),'Retornos da verificação para implementação']]).map(([label,value,hint])=>`<div class="metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(hint)}</small></div>`).join('');
 $('events').innerHTML=sim.logs.slice(0,5).map(log=>`<li><time>${time(log.at)}</time><div><code>${esc(log.event)}</code><span>${esc(log.text)}</span></div></li>`).join('');
 const base=[{path:'.darkside/holocrons/tech.md',skill:'/explore · contexto técnico',state:'Reutilizado'},{path:'.darkside/sith-agents/engineer.md',skill:'Agente específico do projeto',state:'Reutilizado'}];const files=[...base,...sim.artifacts.values()];$('artifactCount').textContent=`${files.length} artefatos`;$('artifactList').innerHTML=files.map(f=>`<div class="artifact-row"><code>${esc(f.path)}</code><span>${esc(f.skill)}</span><span class="state">${esc(f.state)}</span></div>`).join('');
}
function switchScenario(key){const previous=sim;sim=key==='module'?new ModuleSimulation():new Simulation(key);sim.running=previous.running;sim.speed=previous.speed;sim.manual=previous.manual;sim.onChange(updateUI);updateUI();selectStation(sim.phase.station);}
$('scenario').addEventListener('change',e=>switchScenario(e.target.value));
$('kanban').addEventListener('click',e=>{const card=e.target.closest('[data-episode]');if(card&&sim.key==='module'){sim.selectEpisode(card.dataset.episode);selectStation(sim.phase.station);}});
$('playBtn').addEventListener('click',()=>{sim.running=!sim.running;$('playBtn').textContent=sim.running?'Ⅱ':'▶';$('playBtn').setAttribute('aria-label',sim.running?'Pausar simulação':'Continuar simulação');$('playBtn').title=sim.running?'Pausar':'Continuar';updateUI();});$('restartBtn').addEventListener('click',()=>{sim.setScenario(sim.key);selectStation(sim.phase.station);});$('speed').addEventListener('change',e=>sim.speed=Number(e.target.value));$('manualGates').addEventListener('change',e=>{sim.manual=e.target.checked;if(!sim.manual&&sim.key==='module')sim.releaseGates();else if(!sim.manual&&sim.waiting){sim.log('human_decision.created','Gate aprovado automaticamente na simulação');sim.waiting=false;sim.advance();sim.emit();}});$('approveBtn').addEventListener('click',()=>sim.approve());
$('cameraHome').addEventListener('click',()=>{factory?.setCamera('home');$('cameraHome').classList.add('active');$('cameraTop').classList.remove('active');});$('cameraTop').addEventListener('click',()=>{factory?.setCamera('top');$('cameraTop').classList.add('active');$('cameraHome').classList.remove('active');});$('zoomIn').addEventListener('click',()=>factory?.zoom(1.15));$('zoomOut').addEventListener('click',()=>factory?.zoom(1/1.15));$('showTelemetry').addEventListener('change',e=>{if(factory)factory.showEvidence=e.target.checked;});
const guide=$('guide');$('guideBtn').addEventListener('click',()=>guide.showModal());$('closeGuide').addEventListener('click',()=>guide.close());$('beginBtn').addEventListener('click',()=>guide.close());guide.addEventListener('click',e=>{if(e.target===guide){const r=guide.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)guide.close();}});
$('stationPicker').innerHTML=organizations.map(o=>`<option value="${o.id}">Empresa · ${esc(o.name)}</option>`).join('')+stations.map((s,i)=>`<option value="${s.id}">${String(i+1).padStart(2,'0')} · ${esc(s.name)}</option>`).join('');$('stationPicker').addEventListener('change',e=>selectStation(e.target.value));sim.onChange(updateUI);updateUI();selectStation(selected);$('cameraHome').classList.add('active');
async function initializeScene(){
 window.edsaSceneStatus='loading';$('sceneLoading').hidden=false;$('noWebGL').hidden=true;
 if(factory){factory.observer.disconnect();factory.controls.dispose();factory.renderer.dispose();factory=null;}
 const oldCanvas=$('world');const canvas=oldCanvas.cloneNode(false);oldCanvas.replaceWith(canvas);$('labels').replaceChildren();
 try{
  await Promise.race([document.fonts?.ready||Promise.resolve(),new Promise(resolve=>setTimeout(resolve,1500))]);
  factory=new FactoryScene(canvas,$('viewport'),selectStation);factory.select(selected);
  factory.render(0,sim);
  canvas.addEventListener('webglcontextlost',event=>{event.preventDefault();factory=null;window.edsaShowSceneError('A conexão com a renderização 3D foi interrompida.','Tente novamente para reconstruir a cena.');});
  window.edsaSceneStatus='ready';$('sceneLoading').hidden=true;
  for(const id of ['cameraHome','cameraTop','zoomIn','zoomOut'])$(id).disabled=false;
 }catch(error){
  factory=null;$('labels').replaceChildren();
  window.edsaShowSceneError('Não foi possível iniciar a cena 3D.','O navegador não conseguiu iniciar a renderização WebGL. Tente novamente ou abra o link no navegador do dispositivo.');
  for(const id of ['cameraHome','cameraTop','zoomIn','zoomOut'])$(id).disabled=true;
  console.error('Falha ao iniciar cena 3D:',error);
 }
}
window.edsaRetry3D=initializeScene;
await initializeScene();
let last=performance.now(),lastUI=0;function frame(now){const dt=Math.max(0,Math.min((now-last)/1000,.1));last=now;if(!document.hidden){sim.update(dt);if(factory){try{factory.render(dt,sim);}catch(error){factory=null;window.edsaShowSceneError('A cena 3D encontrou um erro.','Tente novamente para reiniciar a visualização.');console.error(error);}}if(now-lastUI>200){$('phaseProgress').style.width=`${Math.min(100,sim.phaseTime/sim.phase.duration*100)}%`;$('simClock').textContent=time(sim.elapsed);if(sim.key==='module')for(const e of sim.episodes){const progress=$('kanban').querySelector(`[data-progress="${e.id}"]`);if(progress)progress.style.width=`${Math.min(100,e.phaseTime/e.phases[e.index].duration*100)}%`;}lastUI=now;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
document.addEventListener('visibilitychange',()=>last=performance.now());
// Estrutura para agentes de navegador. Disponível quando a API WebMCP for suportada.
const modelContext=document.modelContext;
if(modelContext?.registerTool){
 const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 const registered=[{name:'explore_edsa_station',description:'Seleciona uma estação da fábrica EDSA.IA e retorna responsabilidades e artefatos.',inputSchema:{type:'object',properties:{station:{type:'string',enum:entities.map(s=>s.id)}},required:['station'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{if(!input||!entities.some(s=>s.id===input.station))throw Error('Estação inválida');selectStation(input.station);return {station:input.station,responsibilities:entities.find(s=>s.id===input.station).description,parent:entities.find(s=>s.id===input.station).parent||null,children:entities.find(s=>s.id===input.station).children||[]};}},
 {name:'set_edsa_scenario',description:'Seleciona uma jornada fictícia: module, feature, bug ou improve. Reinicia a simulação local.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:['module','feature','bug','improve']}},required:['scenario'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input)=>{if(!input||!['module','feature','bug','improve'].includes(input.scenario))throw Error('Jornada inválida');$('scenario').value=input.scenario;switchScenario(input.scenario);return {episode:sim.episodeId,scenario:sim.scenario.name};}}];
 for(const tool of registered){try{Promise.resolve(modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(error=>console.warn('WebMCP indisponível:',error));}catch(error){console.warn('WebMCP indisponível:',error);}}
}

}
startApp().catch(error=>{console.error(error);window.edsaShowSceneError?.("A fábrica não conseguiu iniciar.","Tente novamente ou abra a página no navegador do dispositivo.");});
